language: java
sudo: false
install: true
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=alanlgoncalves_url-shortener
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: alanlgoncalves
    token:
      secure: "JuOyJBtXzuHJsMzOMYQjSxSLy38550e38xGaGgClrUjiA96xEQ4NXVv7e782mGV5ekhOJpuiI8QdSZmrC8sza8N7kPKVxczpS+fWKJBgGjhqxQa4Rnvp3bqZ7YZvnFq0mPnfb4DPyd2WtIr8JTp2TrDYfCQ1jKKOUIuojrokkkwHI7jJKvdtDTe0/pJg4iG9+7ny8EKNllHjL5z9Oo8gudHg/ysHFfgnYUp45p498o1cH9YWhedmi3vs+J0mkfyhZg4Ilrmm3EK3aP3J6+CmDUf/ZFpT4J2oZkoozGjlLMWmAAnzHQChXT10xEd6ozOdbLtkvzfu8o0g5GrnzfWxHWZnpHBaFFNIvD006ITmV3Ls0rRzd/CInzRpnvH395zKzR5w2Yh5nLJwZa1VvBiiQhMyRZTBEfhFtoYZJPhINHAf/AjMeZv+hGknwrzJfSTNqBu9vnTQvMZsGssLhy2mRNbHjZURhcNKyLiJq/XEuTREp58uojFQvbWy9slUx2TEzmPEU/Ft04EsyAtJvOCdENXqB6dTmRfOF5byqeRZw6qITNQCDFMWGyzQkMlbCPBwUF6R+2/w+RQULNLodd62CEJdFq91SfinWP2NNiL0UiiliWB1zhZc7gHPNMu0PWjRARmcE3imdHiEqsB1SI/FT4pULI23afFyhfAEz0fFA0c="
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
