language: java
sudo: false
install: true
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=alanlgoncalves_url-shortener
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: alanlgoncalves
    token:
      secure: "JQASxOt5SMktab+0VLAMQI5j/GladHUJxv2j0dcXlLIFYQ0YyJXQHcRSbkk74hWE7dwrUGwqjxN+3KnGQbuMxd+DPejBLV/xtlSzO8CCLr6la76zSf5Vz6K1IV83+lI77XDd36Np8RjH69vtOQ+/vz7yN0gcteYBs/rZuoSc6ZF608Q1G/W2FCWohyp2a4GjvUo/tLgDpK/o5dDdqGTCiv6nIv+CF2DMUIG9gkctwxnm1Bhg9dYK3BDvROZKiA0n4LmOJmxZ9QgXTIA/sNyQn3V9FlXazLDhRAlx9gwZ0wN+NStBc+T1FqBqp2ZSE+cLxytTdM/9gxh8z6PKSTmQmCF+FR7RAOnfdUlmMKnuC+79/Z23zaiHHet2LQtpT9Xqd5zb+aUvaOVaWAiuglHiIs+A7gsxwNziSwh5eXcNUfoLd6idZKa7hZ8AYRfckXuQFmD5jfX/jeC4ADP+aIvf4rDE6KvPwvVUo4vyt58A8LnkTS4ji0xeVsJrMaU4J0kFSY8SAwxX2GF6ywp8sT94xLMHZJLk3Zyz843xxvlMuhiO3cteSjsOumjlNkoyeTtqhkQEphjuAasIynzztxFTx/Tqf+iCQuJ/x4RTFuiy1yxhQNqRL806td4t3Gs4ddZOimXl9VKyZs/Im39/tfa1g6Rwax8MgWrQAD3gq2Ft888="
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
