language: java
install: true
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=alanlgoncalves_url-shortener
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: alanlgoncalves
    token:
      secure: h4JKeUJCipV8FTqP6TVkvQpG4xM0BgWNvaYjJPCeZ8QuF1dsy9Ek0QOl/7UjOCpfCFehyUJIH9xXUKp5QSDAaEJtHSVDaCOSvH00YEz6cksXspzTuLWs9wHOuoZVdd8BCTU3pUHw57yNrQ4yAO0FMyjV9sEUH95KvogTgJihdNFYfbimfSgxRGb4dLSQP/g5AeapJgpZn4AD41Fu8d9z+kt6dJuRLhk2UB3U2cRUml4FUQfcLberp7LxTIra5GiAUX+/lEM3R1mIp/JS//uwAXvizQZ856xjoxvED8w3tgpgCc2H6QQ8jlz28yaLsSbpD6d+mppTPX8Fj9FaZ+Zd48Pi50iRf9Ms2baj6n2ekdcqWX0KS8+NdDJc+57TRUdjvn3pp3i6p6n+OGIGz2K4nk0POQKBLlBon/HXGKK8KMVl0Mn/Z/xzShKw/OD34Vk6AYJ2qt8lvXf6wgtGBbOA9LoAwmYHMkkKNOhfoiKh//ikmi+RjdUVbqEDHsXzK/lXOMzX28KaPCJvChD1bvmDxarlFV3XVtXyZvaKr3LLZwO6aC/ApD8Trc8Pp7nyVzD3RBXhhcEtxpMJ0Zem81gNqWrsUFqQTlZRT0REyS7npTjZ410ujNE/JbUtYqLDXir85yJuJO9m6/Y+iA2wxsZb3n/rqfv18b+CcXV3YH49dAw=
cache:
  directories:
    - "$HOME/.m2"
