version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alanlgoncalves/url-shortener-app:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    expose:
      - "5000"
    networks:
      - url-shortener-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017"
    networks:
      - url-shortener-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shortener_rw
      - MONGO_INITDB_ROOT_PASSWORD=7QZjSNbg0cor
      - MONGO_INITDB_DATABASE=dbShortener
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "8080:8080"
    networks:
      - url-shortener-network
networks:
  url-shortener-network:
    driver: bridge