version: '3'
services:
  docker-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alanlgoncalves/url-shortener-app:latest
    container_name: url-shortener-app
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    ports:
      - "8080:8080"
    networks:
      - url-shortener-network
    depends_on:
      - docker-mongodb
  docker-mongodb:
    image: mongo:latest
    container_name: url-shortener-mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - url-shortener-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shortener_rw
      - MONGO_INITDB_ROOT_PASSWORD=7QZjSNbg0cor
      - MONGO_INITDB_DATABASE=dbShortener
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  url-shortener-network:
    driver: bridge