server:
  port: 5000
  host: 127.0.0.1:8080
  default-protocol: http

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: dbShortener
      username: shortener_rw
      password: 7QZjSNbg0cor
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}

