server:
  port: 8080
  host: 127.0.0.1:8080
  default-protocol: http

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: dbShortener
      uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}

