server:
  port: 5000
  host: 35.198.6.215:8080
  default-protocol: http

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: dbShortener
      username: shortener_rw
      password: 7QZjSNbg0cor
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}
  security:
    oauth2:
      client-id: url-shortener
      client-secret: $2a$10$fepI38wWSUOF.LhLuGyVweziHUOJjAZrVLKWdIA1MeiDN6xcjNEoS
      access-token-validity-seconds: 3600
      refresh-token-validity-seconds: 21600
